### ISSUE TITLE
Sorry...

### ISSUE THREAD

**Issue by benjie** [mlipscombe/postgraphile-plugin-nested-mutations#4]
I think 4.1.0 is going to break this plugin. Come chat to me on Discord, so we can try and minimise any issues: http://discord.gg/graphile

**Comment by vincenzo** [comment]
@mlipscombe 

I am actually using this plugin, and after a chat with @benjie I ran a number of tests with `postgraphile@4.1-alpha`. The fixes that @benjie put in place for solving issues with multiple aliased queries within mutation come through the plugin just fine. 

In short, not only does the plugin not break, but what was broken before due to a bug (I presume) in postgraphile, it's now working just fine. 

So, it should be fine to close this issue down.

**Comment by benjie** [comment]
Perfect, thanks for the testing @vincenzo 👍
