### ISSUE TITLE
Plugin removes non-null requirement on inputs

### ISSUE THREAD

**Issue by Munksgaard** [mlipscombe/postgraphile-plugin-nested-mutations#6]
I have the following tables:

```
CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES willoughby.user(id) ON DELETE CASCADE,
  description TEXT NOT NULL
);

CREATE TABLE post_file (
  id SERIAL PRIMARY KEY,
  post_id INTEGER NOT NULL REFERENCES post(id) ON DELETE CASCADE,
  uuid UUID NOT NULL
);
```

Before adding the postgraphile-plugin-nested-mutations plugin to my postgraphile setup, the user_id was required in the PostInput type, but after adding the plugin the user_id is nullable when creating a new post.

**Comment by mlipscombe** [comment]
This is intentional, because you have the possibility of creating a row in `willoughby.user` as a nested mutation, and there's no way in GraphQL to set NotNull conditionally.

In your example, when creating a `post`, you can use the GraphQL field `userId` directly by setting an `Integer` of an existing `user`, or you can create a new user by `userToUserId: { create: { ... } }` or look up a user by any unique column(s) by `userToUserId: { connect: { emailAddress: "john@smith.com" } }`.

**Comment by Munksgaard** [comment]
That makes sense, thank you for explaining.
